#spring:
#  application:
#    name: configserver
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:/C:/Users/heinz/Documents/developments/rws-twitter-to-kafka/twitter-to-kafka-config-server-repository
#          default-label: master
#          clone-on-start: true
#    fail-fast: true

server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG