twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 1000

  retry-config:
    initial-interval-ms: 1000
    max-interval-ms: 10000
    multiplier: 2.0
    maxAttempts: 3
    sleep-time-ms: 2000

  kafka-config:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
    schema-registry-url-key: schema.registry.url
    schema-registry-url: http://localhost:8081
    topic-name: twitter-topic
    topic-names-to-create:
      - twitter-topic
    num-of-partitions: 3
    replication-factor: 3

  kafka-producer-config:
    keySerializerClass: org.apache.kafka.common.serialization.LongSerializer
    valueSerializerClass: io.confluent.kafka.serializers.KafkaAvroSerializer
    compressionType: snappy
    acks: all
    batchSize: 16384
    batchSizeBoostFactor: 100
    lingerMs: 5
    requestTimeoutMs: 60000
    retryCount: 5